// Autogenerated from Pigeon (v4.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Story;
@class Comment;

@interface Story : NSObject
+ (instancetype)makeWithTitle:(nullable NSString *)title
    author:(nullable NSString *)author
    comments:(nullable NSArray<Comment *> *)comments
    rates:(nullable NSNumber *)rates
    year:(nullable NSNumber *)year
    isFavorite:(nullable NSNumber *)isFavorite;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * author;
@property(nonatomic, strong, nullable) NSArray<Comment *> * comments;
@property(nonatomic, strong, nullable) NSNumber * rates;
@property(nonatomic, strong, nullable) NSNumber * year;
@property(nonatomic, strong, nullable) NSNumber * isFavorite;
@end

@interface Comment : NSObject
+ (instancetype)makeWithUser:(nullable NSString *)user
    body:(nullable NSString *)body;
@property(nonatomic, copy, nullable) NSString * user;
@property(nonatomic, copy, nullable) NSString * body;
@end

/// The codec used by HostStoryApi.
NSObject<FlutterMessageCodec> *HostStoryApiGetCodec(void);

@protocol HostStoryApi
- (nullable Story *)respondWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HostStoryApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostStoryApi> *_Nullable api);

NS_ASSUME_NONNULL_END
