import 'package:online_supermarket/models/item.dart';

List<Item> itemListDB = [
  Item(
    name: 'にんじん',
    imagePath: 'assets/images/carrot.png',
    count: 0,
    price: 100,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'キャベツ',
    imagePath: 'assets/images/cabbage.png',
    count: 0,
    price: 120,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'じゃがいも',
    imagePath: 'assets/images/potato.png',
    count: 0,
    price: 80,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'たまねぎ',
    imagePath: 'assets/images/onion.png',
    count: 0,
    price: 50,
    category: MyCategory.vegetables,
  ),
  Item(
    name: '豚肉',
    imagePath: 'assets/images/pork.png',
    count: 0,
    price: 300,
    category: MyCategory.meat,
  ),
  Item(
    name: '牛肉',
    imagePath: 'assets/images/beef.png',
    count: 0,
    price: 500,
    category: MyCategory.meat,
  ),
  Item(
    name: '卵',
    imagePath: 'assets/images/eggs.png',
    count: 0,
    price: 200,
    category: MyCategory.meat,
  ),
  Item(
    name: 'アボカド',
    imagePath: 'assets/images/avocado.png',
    count: 0,
    price: 100,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'りんご',
    imagePath: 'assets/images/apple.png',
    count: 0,
    price: 110,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'バナナ',
    imagePath: 'assets/images/bananas.png',
    count: 0,
    price: 180,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'さかな',
    imagePath: 'assets/images/fish.png',
    count: 0,
    price: 300,
    category: MyCategory.meat,
  ),
  Item(
    name: '羊肉',
    imagePath: 'assets/images/lamb.png',
    count: 0,
    price: 180,
    category: MyCategory.meat,
  ),
  Item(
    name: 'メロン',
    imagePath: 'assets/images/melon.png',
    count: 0,
    price: 1000,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'オレンジ',
    imagePath: 'assets/images/orange.png',
    count: 0,
    price: 200,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'もも',
    imagePath: 'assets/images/peach.png',
    count: 0,
    price: 300,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'パイナップル',
    imagePath: 'assets/images/pineapple.png',
    count: 0,
    price: 180,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'いちご',
    imagePath: 'assets/images/strawberry.png',
    count: 0,
    price: 400,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'トマト',
    imagePath: 'assets/images/tomato.png',
    count: 0,
    price: 100,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'スイカ',
    imagePath: 'assets/images/watermelon.png',
    count: 0,
    price: 500,
    category: MyCategory.fruits,
  ),
  Item(
    name: 'アスパラガス',
    imagePath: 'assets/images/asparagus.png',
    count: 0,
    price: 200,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'ブロッコリー',
    imagePath: 'assets/images/broccoli.png',
    count: 0,
    price: 150,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'とうもろこし',
    imagePath: 'assets/images/corn.png',
    count: 0,
    price: 170,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'きゅうり',
    imagePath: 'assets/images/cucumber.png',
    count: 0,
    price: 100,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'ガーリック',
    imagePath: 'assets/images/garlic.png',
    count: 0,
    price: 100,
    category: MyCategory.vegetables,
  ),
  Item(
    name: 'パプリカ',
    imagePath: 'assets/images/paprika.png',
    count: 0,
    price: 100,
    category: MyCategory.vegetables,
  ),
];
